services:
  - type: web
    name: riffly-backend
    env: node
    repo: https://github.com/Borges2023/riffly2.0
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm --prefix apps/api start
    healthCheckPath: /api/
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
